#
# Autogenerated by Thrift Compiler (0.9.2)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'thrift'
require 'users_types'

module UsersService
  class Client
    include ::Thrift::Client

    def find()
      send_find()
      return recv_find()
    end

    def send_find()
      send_message('find', Find_args)
    end

    def recv_find()
      result = receive_message(Find_result)
      return result.success unless result.success.nil?
      raise result.e unless result.e.nil?
      raise ::Thrift::ApplicationException.new(::Thrift::ApplicationException::MISSING_RESULT, 'find failed: unknown result')
    end

  end

  class Processor
    include ::Thrift::Processor

    def process_find(seqid, iprot, oprot)
      args = read_args(iprot, Find_args)
      result = Find_result.new()
      begin
        result.success = @handler.find()
      rescue ::ServiceException => e
        result.e = e
      end
      write_result(result, oprot, 'find', seqid)
    end

  end

  # HELPER FUNCTIONS AND STRUCTURES

  class Find_args
    include ::Thrift::Struct, ::Thrift::Struct_Union

    FIELDS = {

    }

    def struct_fields; FIELDS; end

    def validate
    end

    ::Thrift::Struct.generate_accessors self
  end

  class Find_result
    include ::Thrift::Struct, ::Thrift::Struct_Union
    SUCCESS = 0
    E = 1

    FIELDS = {
      SUCCESS => {:type => ::Thrift::Types::STRUCT, :name => 'success', :class => ::User},
      E => {:type => ::Thrift::Types::STRUCT, :name => 'e', :class => ::ServiceException}
    }

    def struct_fields; FIELDS; end

    def validate
    end

    ::Thrift::Struct.generate_accessors self
  end

end

