#
# Autogenerated by Thrift Compiler (1.0.0-dev)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'thrift'
require 'users_types'

module UsersService
  class Client
    include ::Thrift::Client

    def find(id)
      send_find(id)
      return recv_find()
    end

    def send_find(id)
      send_message('find', Find_args, :id => id)
    end

    def recv_find()
      result = receive_message(Find_result)
      return result.success unless result.success.nil?
      raise result.e unless result.e.nil?
      raise ::Thrift::ApplicationException.new(::Thrift::ApplicationException::MISSING_RESULT, 'find failed: unknown result')
    end

    def create(user)
      send_create(user)
      return recv_create()
    end

    def send_create(user)
      send_message('create', Create_args, :user => user)
    end

    def recv_create()
      result = receive_message(Create_result)
      return result.success unless result.success.nil?
      raise result.e unless result.e.nil?
      raise ::Thrift::ApplicationException.new(::Thrift::ApplicationException::MISSING_RESULT, 'create failed: unknown result')
    end

  end

  class Processor
    include ::Thrift::Processor

    def process_find(seqid, iprot, oprot)
      args = read_args(iprot, Find_args)
      result = Find_result.new()
      begin
        result.success = @handler.find(args.id)
      rescue ::ServiceException => e
        result.e = e
      end
      write_result(result, oprot, 'find', seqid)
    end

    def process_create(seqid, iprot, oprot)
      args = read_args(iprot, Create_args)
      result = Create_result.new()
      begin
        result.success = @handler.create(args.user)
      rescue ::ServiceException => e
        result.e = e
      end
      write_result(result, oprot, 'create', seqid)
    end

  end

  # HELPER FUNCTIONS AND STRUCTURES

  class Find_args
    include ::Thrift::Struct, ::Thrift::Struct_Union
    ID = 1

    FIELDS = {
      ID => {:type => ::Thrift::Types::I64, :name => 'id'}
    }

    def struct_fields; FIELDS; end

    def validate
    end

    ::Thrift::Struct.generate_accessors self
  end

  class Find_result
    include ::Thrift::Struct, ::Thrift::Struct_Union
    SUCCESS = 0
    E = 1

    FIELDS = {
      SUCCESS => {:type => ::Thrift::Types::STRUCT, :name => 'success', :class => ::User},
      E => {:type => ::Thrift::Types::STRUCT, :name => 'e', :class => ::ServiceException}
    }

    def struct_fields; FIELDS; end

    def validate
    end

    ::Thrift::Struct.generate_accessors self
  end

  class Create_args
    include ::Thrift::Struct, ::Thrift::Struct_Union
    USER = 1

    FIELDS = {
      USER => {:type => ::Thrift::Types::STRUCT, :name => 'user', :class => ::User}
    }

    def struct_fields; FIELDS; end

    def validate
    end

    ::Thrift::Struct.generate_accessors self
  end

  class Create_result
    include ::Thrift::Struct, ::Thrift::Struct_Union
    SUCCESS = 0
    E = 1

    FIELDS = {
      SUCCESS => {:type => ::Thrift::Types::STRUCT, :name => 'success', :class => ::User},
      E => {:type => ::Thrift::Types::STRUCT, :name => 'e', :class => ::ServiceException}
    }

    def struct_fields; FIELDS; end

    def validate
    end

    ::Thrift::Struct.generate_accessors self
  end

end

