#
# Autogenerated by Thrift Compiler (0.9.2)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'thrift'

class User
  include ::Thrift::Struct, ::Thrift::Struct_Union
  ID = 1
  FIRST_NAME = 2
  LAST_NAME = 3
  EMAIL = 4

  FIELDS = {
    ID => {:type => ::Thrift::Types::I64, :name => 'id', :optional => true},
    FIRST_NAME => {:type => ::Thrift::Types::STRING, :name => 'first_name'},
    LAST_NAME => {:type => ::Thrift::Types::STRING, :name => 'last_name'},
    EMAIL => {:type => ::Thrift::Types::STRING, :name => 'email'}
  }

  def struct_fields; FIELDS; end

  def validate
    raise ::Thrift::ProtocolException.new(::Thrift::ProtocolException::UNKNOWN, 'Required field first_name is unset!') unless @first_name
    raise ::Thrift::ProtocolException.new(::Thrift::ProtocolException::UNKNOWN, 'Required field last_name is unset!') unless @last_name
    raise ::Thrift::ProtocolException.new(::Thrift::ProtocolException::UNKNOWN, 'Required field email is unset!') unless @email
  end

  ::Thrift::Struct.generate_accessors self
end

